"""Add column pass_secure for storing passwords

Revision ID: 0a63dc36c3b2
Revises: e34c84c48c61
Create Date: 2017-10-23 16:38:02.302281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a63dc36c3b2'
down_revision = 'e34c84c48c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
